### ISSUE TITLE
The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by thewhitewayofdelight** [UniGameTeam/UniGame.GoogleSpreadsheetsImporter#7]
Hi,

I just install the package by adding the Unity and UniGame to scopedRegistries in manifest.json then install UniGames Google Spreadsheest to Unity via the package manager.

Then after opening the project, this error shows up.
Any advice?

![Screen Shot 2022-03-01 at 15 32 18](https://user-images.githubusercontent.com/87333145/156133456-40d074fe-44f1-4f4c-9e02-ba2617de9501.png)

**Comment by Mefodei** [comment]
done
