### ISSUE TITLE
are you missing a using directive or an assembly reference?

### ISSUE THREAD

**Issue by thewhitewayofdelight** [UniGameTeam/UniGame.GoogleSpreadsheetsImporter#8]
Hello,
I'm having trouble installing this package @_@.
Here is what I did:

* I just created new Unity 2020.3.27f1 project.
* Then add this code to my manifest.json
```
  "scopedRegistries": [
    {
      "name": "Unity",
      "url": "https://packages.unity.com",
      "scopes": [
        "com.unity"
      ]
    },
    {
      "name": "UniGame",
      "url": "http://packages.unigame.pro:4873/",
      "scopes": [
        "com.unigame"
      ]
    }
  ]
```
* Install UniGames Google Spreadsheets to Unity through Package Manager.
* Then, this error show up

<img width="840" alt="Screen Shot 2022-03-01 at 23 29 44" src="https://user-images.githubusercontent.com/87333145/156208690-a1a8aba3-27f0-4fe9-a336-13f087af285f.png">

Thank you for your attention!

**Comment by Mefodei** [comment]
Hello there. I will check that issue asap. Thx

**Comment by Mefodei** [comment]
done
